<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <!-- NuGet properties-->
    <Title>Crest Localization</Title>
    <Description>$(OCFrameworkDescription)

    Provides the infrastructure necessary to support localized string using the PO (Portable Object) localization file format.
    It also supports plural forms.
    </Description>
    <PackageTags>$(PackageTags) PlatformFramework Localization</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Admin.Abstractions\Crest.Admin.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Apis.GraphQL.Abstractions\Crest.Apis.GraphQL.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.ContentManagement.GraphQL\Crest.ContentManagement.GraphQL.csproj" />
    <ProjectReference Include="..\Crest.DisplayManagement\Crest.DisplayManagement.csproj" />
    <ProjectReference Include="..\Crest.Localization.Core\Crest.Localization.Core.csproj" />
    <ProjectReference Include="..\Crest.Module.Targets\Crest.Module.Targets.csproj" />
    <ProjectReference Include="..\Crest.Navigation.Core\Crest.Navigation.Core.csproj" />
    <ProjectReference Include="..\Crest.ResourceManagement\Crest.ResourceManagement.csproj" />
    <ProjectReference Include="..\Crest.Settings.Core\Crest.Settings.Core.csproj" />
  </ItemGroup>

</Project>
