<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- NuGet properties-->
    <Title>Crest Media Core</Title>
    <Description>$(OCCMSDescription)

    Core implementation for Crest Media.</Description>
    <PackageTags>$(PackageTags) PlatformCMS ContentManagement</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.FileStorage.Abstractions\Crest.FileStorage.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Infrastructure.Abstractions\Crest.Infrastructure.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Media.Abstractions\Crest.Media.Abstractions.csproj" />
  </ItemGroup>

</Project>
