<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Crest.Infrastructure</RootNamespace>
    <!-- NuGet properties-->
    <Title>Crest Infrastructure Abstractions</Title>
    <Description>$(OCCMSDescription)

    Abstractions for PlatformCMS Infrastructure </Description>
    <PackageTags>$(PackageTags) PlatformCMS Infrastructure Abstractions</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Crest.Infrastructure" />
    <InternalsVisibleTo Include="Crest.Tests" />
    <InternalsVisibleTo Include="Crest.Abstractions.Tests" />
    <InternalsVisibleTo Include="Crest.Data.YesSql" />
    <InternalsVisibleTo Include="Crest.ContentManagement.GraphQL" />
    <InternalsVisibleTo Include="Crest.DisplayManagement" />
    <InternalsVisibleTo Include="Crest.DynamicCache" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Abstractions\Crest.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.ResourceManagement.Abstractions\Crest.ResourceManagement.Abstractions.csproj" />
  </ItemGroup>

</Project>
