using System.Reflection;
using Crest.Workflows.Studio.Contracts;
using Crest.Workflows.Studio.Models;
using JetBrains.Annotations;

namespace Crest.Workflows.Studio.Services;

/// <summary>
/// Provides client information by extracting metadata from the executing assembly.
/// </summary>
[UsedImplicitly]
public class AssemblyClientInformationProvider : IClientInformationProvider
{
    /// <inheritdoc />
    public ValueTask<ClientInformation> GetInfoAsync(CancellationToken cancellationToken = default)
    {
        var assembly = Assembly.GetExecutingAssembly();
        var versionAttribute = assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>();
        var version = RemoveAutoGeneratedPostfix(versionAttribute);

        return new(new ClientInformation(version));
    }

    private static string RemoveAutoGeneratedPostfix(AssemblyInformationalVersionAttribute? versionAttribute)
    {
        return versionAttribute?.InformationalVersion.Split("+")[0]!;
    }
}