<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Crest.Lucene</RootNamespace>
    <!-- NuGet properties-->
    <Title>Crest Lucene Core</Title>
    <Description>$(OCCMSDescription)

    Core Implementation for Lucene module.</Description>
    <PackageTags>$(PackageTags) PlatformCMS</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lucene.Net.QueryParser" />
    <PackageReference Include="Lucene.Net.Spatial" />
    <ProjectReference Include="..\Crest.Abstractions\Crest.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Contents.Core\Crest.Contents.Core.csproj" />
    <ProjectReference Include="..\Crest.Indexing.Abstractions\Crest.Indexing.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Indexing.Core\Crest.Indexing.Core.csproj" />
    <ProjectReference Include="..\Crest.Queries.Abstractions\Crest.Queries.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Search.Lucene.Abstractions\Crest.Search.Lucene.Abstractions.csproj" />
  </ItemGroup>

</Project>
