<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Crest.Indexing</RootNamespace>
    <!-- NuGet properties-->
    <Title>Crest Indexing Abstractions</Title>
    <Description>$(OCCMSDescription)

    Abstractions for Indexing.</Description>
    <PackageTags>$(PackageTags) PlatformCMS Abstractions</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.ContentManagement.Abstractions\Crest.ContentManagement.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Infrastructure.Abstractions\Crest.Infrastructure.Abstractions.csproj" />
  </ItemGroup>

</Project>
