<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="$(PlatformSrcDir)OrchardCore\OrchardCore.Module.Targets\OrchardCore.Module.Targets.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore.Modules\OrchardCore.Contents\OrchardCore.Contents.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore\OrchardCore.Module.Targets\OrchardCore.Module.Targets.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore\OrchardCore.ContentManagement\OrchardCore.ContentManagement.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore.Modules\OrchardCore.Title\OrchardCore.Title.csproj" />
  </ItemGroup>

  <ItemGroup Label="Crest.Workflows">
    <ProjectReference Include="..\engine\src\modules\Crest.Workflows.Expressions.JavaScript\Crest.Workflows.Expressions.JavaScript.csproj" />
    <ProjectReference Include="..\engine\src\modules\Crest.Workflows.Core\Crest.Workflows.Core.csproj" />
    <ProjectReference Include="..\engine\src\modules\Crest.Workflows.Management\Crest.Workflows.Management.csproj" />
    <ProjectReference Include="..\engine\src\modules\Crest.Workflows.Runtime\Crest.Workflows.Runtime.csproj" />
    <ProjectReference Include="..\engine\src\modules\Crest.Workflows.Engine\Crest.Workflows.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Server\Crest.Workflows.csproj" />
  </ItemGroup>

  <Import Project="$(PlatformSrcDir)OrchardCore\OrchardCore.Module.Targets\OrchardCore.Module.Targets.targets" />
</Project>
