<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
     <!-- NuGet properties-->
    <Title>Crest Feeds</Title>
    <Description>$(OCFrameworkDescription)

    Feeds module adds RSS feeds capabilities.</Description>
    <PackageTags>$(PackageTags) PlatformFramework RSS</PackageTags>

  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.DisplayManagement\Crest.DisplayManagement.csproj" />
    <ProjectReference Include="..\Crest.Module.Targets\Crest.Module.Targets.csproj" />
    <ProjectReference Include="..\Crest.Feeds.Core\Crest.Feeds.Core.csproj" />
  </ItemGroup>

</Project>
