<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.Authorization" Version="10.0.11" />
    <PackageVersion Include="Microsoft.AspNetCore.Components" Version="10.0.11" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="10.0.11" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Forms" Version="10.0.11" />
    <PackageVersion Include="Crest.Admin.Abstractions" Version="4.0.0-local" />
    <PackageVersion Include="Crest.ContentManagement" Version="4.0.0-local" />
    <PackageVersion Include="Crest.DisplayManagement" Version="4.0.0-local" />
    <PackageVersion Include="Crest.Email.Abstractions" Version="4.0.0-local" />
    <PackageVersion Include="Crest.Menu" Version="4.0.0-local" />
    <PackageVersion Include="Crest.Module.Targets" Version="4.0.0-local" />
    <PackageVersion Include="Crest.ResourceManagement" Version="4.0.0-local" />
    <PackageVersion Include="Crest.Setup" Version="4.0.0-local" />
    <PackageVersion Include="Crest.Setup.Abstractions" Version="4.0.0-local" />
    <PackageVersion Include="Crest.Users" Version="4.0.0-local" />
    <PackageVersion Include="Crest.Users.Abstractions" Version="4.0.0-local" />
    <PackageVersion Include="Radzen.Blazor" Version="11.0.4" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="Verify.XunitV3" Version="31.27.0" />
    <PackageVersion Include="NSubstitute" Version="6.0.0" />
  </ItemGroup>
</Project>
