<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="$(PlatformSrcDir)OrchardCore\OrchardCore.Module.Targets\OrchardCore.Module.Targets.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore\OrchardCore.Admin.Abstractions\OrchardCore.Admin.Abstractions.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore.Modules\OrchardCore.Contents\OrchardCore.Contents.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore\OrchardCore.Infrastructure\OrchardCore.Infrastructure.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore\OrchardCore.Module.Targets\OrchardCore.Module.Targets.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore\OrchardCore.ContentManagement\OrchardCore.ContentManagement.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore\OrchardCore.ContentTypes.Abstractions\OrchardCore.ContentTypes.Abstractions.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore\OrchardCore.DisplayManagement\OrchardCore.DisplayManagement.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore\OrchardCore.Navigation.Core\OrchardCore.Navigation.Core.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore\OrchardCore.ResourceManagement\OrchardCore.ResourceManagement.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore\OrchardCore.Roles.Abstractions\OrchardCore.Roles.Abstractions.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore\OrchardCore.Workflows.Abstractions\OrchardCore.Workflows.Abstractions.csproj" />
    <PackageReference Include="System.Linq.Dynamic.Core" />
  </ItemGroup>

  <ItemGroup Label="Crest.Workflows">
    <ProjectReference Include="..\engine\src\modules\Crest.Workflows.Engine\Crest.Workflows.Engine.csproj" />
    <ProjectReference Include="..\engine\src\modules\Crest.Workflows.Expressions.JavaScript\Crest.Workflows.Expressions.JavaScript.csproj" />
    <ProjectReference Include="..\engine\src\modules\Crest.Workflows.Expressions.Liquid\Crest.Workflows.Expressions.Liquid.csproj" />
    <ProjectReference Include="..\engine\src\modules\Crest.Workflows.Http\Crest.Workflows.Http.csproj" />
    <ProjectReference Include="..\engine\src\modules\Crest.Workflows.Api\Crest.Workflows.Api.csproj" />
    <ProjectReference Include="..\engine\src\modules\Crest.Workflows.Runtime.Distributed\Crest.Workflows.Runtime.Distributed.csproj" />
    <ProjectReference Include="..\engine\src\modules\Crest.Workflows.Resilience\Crest.Workflows.Resilience.csproj" />
    <ProjectReference Include="..\engine\src\modules\Crest.Workflows.Scheduling\Crest.Workflows.Scheduling.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Crest.Workflows.Domain.csproj" />
    <ProjectReference Include="..\..\Crest.Server\Crest.csproj" />
  </ItemGroup>

  <Import Project="$(PlatformSrcDir)OrchardCore\OrchardCore.Module.Targets\OrchardCore.Module.Targets.targets" />
</Project>
