<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- NuGet properties-->
    <Title>Crest Infrastructure</Title>
    <Description>$(OCCMSDescription)

    Implementation for PlatformCMS Infrastructure </Description>
    <PackageTags>$(PackageTags) PlatformCMS Infrastructure</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlSanitizer" />
    <PackageReference Include="libphonenumber-csharp" />
    <PackageReference Include="MimeKit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Core\Crest.Core.csproj" />
    <ProjectReference Include="..\Crest.Data.YesSql\Crest.Data.YesSql.csproj" />
    <ProjectReference Include="..\Crest.Infrastructure.Abstractions\Crest.Infrastructure.Abstractions.csproj" />
  </ItemGroup>

</Project>
