<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- NuGet properties-->
    <Title>Crest Features Core</Title>
    <Description>$(OCFrameworkDescription)

    Core implementation of Features Module.</Description>
    <PackageTags>$(PackageTags) PlatformFramework Features</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.DisplayManagement\Crest.DisplayManagement.csproj" />
  </ItemGroup>

</Project>
