<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- NuGet properties-->
    <Title>Target for Crest Theme</Title>
    <Description>$(OCCMSDescription)

    Converts project/library into an Crest Theme that can be referenced in Crest CMS application.</Description>
    <PackageTags>$(PackageTags) PlatformCMS</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <!--
    Add the necessary '.props' and '.targets' files under the 'build\' folder of this package,
    so that a referencing project is built / packed and considered as an 'Crest' theme.

    When packaging a project that references this package, and that targets multiple TFMs, the
    scripts under the 'build\' folder are not executed, so we pack another '.props' file under
    the 'buildMultiTargeting\' folder, that will just import the one under the `build\` folder.
  -->

  <ItemGroup>
    <None Include="Crest.Theme.Targets.props" Pack="true">
      <PackagePath>build\Crest.Theme.Targets.props</PackagePath>
    </None>
    <None Include="buildMultiTargeting\Crest.Theme.Targets.props" Pack="true">
      <PackagePath>buildMultiTargeting\Crest.Theme.Targets.props</PackagePath>
    </None>
    <None Include="Crest.Theme.Targets.targets" Pack="true">
      <PackagePath>build\Crest.Theme.Targets.targets</PackagePath>
    </None>
    <None Include="buildMultiTargeting\Crest.Theme.Targets.targets" Pack="true">
      <PackagePath>buildMultiTargeting\Crest.Theme.Targets.targets</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Crest.Module.Targets\Crest.Module.Targets.csproj" PrivateAssets="none" />
  </ItemGroup>

</Project>
