<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <!-- NuGet properties-->
    <Title>Crest Elasticsearch</Title>
    <Description>
      $(OCCMSDescription)

      Creates Elasticsearch Search indexes to support search scenarios, introduces a preconfigured container-enabled content type.</Description>
    <PackageTags>$(PackageTags) PlatformCMS</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Admin.Abstractions\Crest.Admin.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Module.Targets\Crest.Module.Targets.csproj" />
    <ProjectReference Include="..\Crest.ContentManagement.GraphQL\Crest.ContentManagement.GraphQL.csproj" />
    <ProjectReference Include="..\Crest.DisplayManagement\Crest.DisplayManagement.csproj" />
    <ProjectReference Include="..\Crest.Navigation.Core\Crest.Navigation.Core.csproj" />
    <ProjectReference Include="..\Crest.Queries.Core\Crest.Queries.Core.csproj" />
    <ProjectReference Include="..\Crest.ResourceManagement\Crest.ResourceManagement.csproj" />
    <ProjectReference Include="..\Crest.Elasticsearch.Core\Crest.Elasticsearch.Core.csproj" />
  </ItemGroup>

</Project>
