<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <!-- NuGet properties-->
    <Title>Crest Media Amazon S3</Title>
    <Description>$(OCCMSDescription)

      Enables support for storing media files in Amazon S3 Bucket.</Description>
    <PackageTags>$(PackageTags) PlatformCMS ContentManagement</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Crest.Tests.Integration" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Crest.Admin.Abstractions\Crest.Admin.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.ContentManagement.Display\Crest.ContentManagement.Display.csproj" />
    <ProjectReference Include="..\Crest.FileStorage.AmazonS3\Crest.FileStorage.AmazonS3.csproj" />
    <ProjectReference Include="..\Crest.Infrastructure.Abstractions\Crest.Infrastructure.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Media.Abstractions\Crest.Media.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Media.Core\Crest.Media.Core.csproj" />
    <ProjectReference Include="..\Crest.Module.Targets\Crest.Module.Targets.csproj" />
    <ProjectReference Include="..\Crest.Navigation.Core\Crest.Navigation.Core.csproj" />
    <ProjectReference Include="..\Crest.Media\Crest.Media.csproj" />
  </ItemGroup>


</Project>
