<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <!-- NuGet properties-->
    <Title>Crest Setup</Title>
    <Description>$(OCCMSDescription)

    The setup module is creating the application's setup experience..</Description>
    <PackageTags>$(PackageTags) PlatformCMS</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Crest.Localization\ModularPoFileLocationProvider.cs" Link="ModularPoFileLocationProvider.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Data\Crest.Data.csproj" />
    <ProjectReference Include="..\Crest.DisplayManagement\Crest.DisplayManagement.csproj" />
    <ProjectReference Include="..\Crest.Infrastructure.Abstractions\Crest.Infrastructure.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Localization\Crest.Localization.csproj" />
    <ProjectReference Include="..\Crest.Module.Targets\Crest.Module.Targets.csproj" />
    <ProjectReference Include="..\Crest.Recipes.Abstractions\Crest.Recipes.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Abstractions\Crest.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Setup.Abstractions\Crest.Setup.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YesSql" />
  </ItemGroup>

</Project>
