<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Crest.UrlRewriting</RootNamespace>
    <!-- NuGet properties-->
    <Title>Crest UrlRewriting Abstractions</Title>
    <Description>
      $(OCCMSDescription)

      Abstractions for the UrlRewriting module.
    </Description>
    <PackageTags>$(PackageTags) Crest Abstractions</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Infrastructure.Abstractions\Crest.Infrastructure.Abstractions.csproj" />
  </ItemGroup>

</Project>
