<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>
            Provides services to generate SAS tokens.
        </Description>
        <PackageTags>crestWorkflows module security sas tokens</PackageTags>
    </PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	
    <ItemGroup>
      <ProjectReference Include="..\..\common\Crest.Workflows.Features\Crest.Workflows.Features.csproj" />
    </ItemGroup>
</Project>
