<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\Crest.Build\Crest.Commons.props" />
  <Import Project="..\..\..\Crest.Theme.Targets\Crest.Theme.Targets.props" />
  <Import Project="..\..\..\Crest.Module.Targets\Crest.Module.Targets.props" />

  <PropertyGroup>
    <TargetFrameworks>$(CommonTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Crest.Theme.Targets\Crest.Theme.Targets.csproj" />
    <ProjectReference Include="..\..\..\Crest.DisplayManagement\Crest.DisplayManagement.csproj" />
  </ItemGroup>

  <Import Project="..\..\..\Crest.Module.Targets\Crest.Module.Targets.targets" />
  <Import Project="..\..\..\Crest.Build\Crest.Commons.targets" />

</Project>
