<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Core Crest.Workflows Studio services.</Description>
        <PackageTags>crestWorkflows studio core</PackageTags>
        <RootNamespace>Crest.Workflows.Studio</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Authorization"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.CustomElements"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
        <PackageReference Include="Microsoft.JSInterop"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Blazored.FluentValidation"/>
        <PackageReference Include="Blazored.LocalStorage"/>
        <PackageReference Include="CodeBeam.MudBlazor.Extensions"/>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="MudBlazor"/>
        <PackageReference Include="Radzen.Blazor"/>
        <PackageReference Include="ShortGuid"/>
        <PackageReference Include="ThrottleDebounce"/>
    </ItemGroup>

    <ItemGroup Label="Crest.Workflows" Condition="'$(UseProjectReferences)' == 'true'">
        <ProjectReference Include="..\..\..\..\engine\src\clients\Crest.Workflows.Api.Client\Crest.Workflows.Api.Client.csproj" />
    </ItemGroup>

    <ItemGroup Label="Crest.Workflows" Condition="'$(UseProjectReferences)' != 'true'">
        <PackageReference Include="Crest.Workflows.Api.Client"/>
    </ItemGroup>

</Project>
