<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(PlatformSrcDir)Crest.Module.Targets\Crest.Module.Targets.props" />

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <IsPackable>true</IsPackable>
        <PackageId>Crest.Workflows.Queries</PackageId>
        <PackageTags>Crest;Crest;Workflows;Queries</PackageTags>
        <Description>Provides Crest.Workflows workflow activities for executing Crest queries. Enables workflow integration with SQL queries and other query sources.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations"/>
        <ProjectReference Include="$(PlatformSrcDir)Crest.DisplayManagement\Crest.DisplayManagement.csproj" />
        <ProjectReference Include="$(PlatformSrcDir)Crest.Module.Targets\Crest.Module.Targets.csproj" />
        <ProjectReference Include="$(PlatformSrcDir)Crest.Queries\Crest.Queries.csproj" />
        <PackageReference Include="YesSql.Abstractions" />
    </ItemGroup>

    <ItemGroup Label="Crest.Workflows">
        <PackageReference Include="Crest.Workflows.Sql"/>
        <PackageReference Include="Crest.Workflows.Engine"/>
    </ItemGroup>
</Project>
