<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Crest.Liquid</RootNamespace>
    <!-- NuGet properties-->
    <Title>Crest Liquid Abstractions</Title>
    <Description>$(OCFrameworkDescription)

    Abstractions for liquid syntax.</Description>
    <PackageTags>$(PackageTags) PlatformFramework Liquid</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fluid.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Infrastructure.Abstractions\Crest.Infrastructure.Abstractions.csproj" />
  </ItemGroup>

</Project>
