<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- NuGet properties-->
    <Title>Crest HealthChecks</Title>
    <Description>$(OCFrameworkDescription)

    This module provides health checks for the website.</Description>
    <PackageTags>$(PackageTags) PlatformFramework Infrastructure</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.HealthChecks.Abstractions\Crest.HealthChecks.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Module.Targets\Crest.Module.Targets.csproj" />
  </ItemGroup>

</Project>
