<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Crest.Email</RootNamespace>
    <!-- NuGet properties-->
    <Title>Crest Email Core</Title>
    <Description>
      $(OCFrameworkDescription)

      Core implementation of Email Module.
    </Description>
    <PackageTags>$(PackageTags) PlatformFramework Email</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Email.Abstractions\Crest.Email.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Infrastructure.Abstractions\Crest.Infrastructure.Abstractions.csproj" />
  </ItemGroup>

</Project>
