<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(PlatformSrcDir)OrchardCore\OrchardCore.Module.Targets\OrchardCore.Module.Targets.props" />

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <IsPackable>true</IsPackable>
        <PackageId>Crest.Workflows.Queries</PackageId>
        <PackageTags>OrchardCore;Crest;Workflows;Queries</PackageTags>
        <Description>Provides Crest.Workflows workflow activities for executing Orchard Core queries. Enables workflow integration with SQL queries and other query sources.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations"/>
        <ProjectReference Include="$(PlatformSrcDir)OrchardCore\OrchardCore.DisplayManagement\OrchardCore.DisplayManagement.csproj" />
        <ProjectReference Include="$(PlatformSrcDir)OrchardCore\OrchardCore.Module.Targets\OrchardCore.Module.Targets.csproj" />
        <ProjectReference Include="$(PlatformSrcDir)OrchardCore.Modules\OrchardCore.Queries\OrchardCore.Queries.csproj" />
        <PackageReference Include="YesSql.Abstractions" />
    </ItemGroup>

    <ItemGroup Label="Crest.Workflows">
        <PackageReference Include="Crest.Workflows.Sql"/>
        <PackageReference Include="Crest.Workflows.Engine"/>
    </ItemGroup>

  <Import Project="$(PlatformSrcDir)OrchardCore\OrchardCore.Module.Targets\OrchardCore.Module.Targets.targets" />
</Project>
