<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Crest.Roles</RootNamespace>
    <!-- NuGet properties-->
    <Title>Crest Roles Core</Title>
    <Description>
      $(OCCMSDescription)

      Core implementation for Roles module.
    </Description>
    <PackageTags>$(PackageTags) PlatformCMS</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Crest.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Infrastructure.Abstractions\Crest.Infrastructure.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Roles.Abstractions\Crest.Roles.Abstractions.csproj" />
  </ItemGroup>

</Project>
