<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Crest.Apis.GraphQL</RootNamespace>

    <!-- NuGet properties-->
    <Title>Crest GraphQL Apis Abstractions</Title>
    <Description>$(OCFrameworkDescription)

    Abstractions for GraphQL Apis</Description>
    <PackageTags>$(PackageTags) PlatformFramework GraphQL Apis Abstractions</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GraphQL" />
    <PackageReference Include="GraphQL.DataLoader" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.DisplayManagement.Abstractions\Crest.DisplayManagement.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Infrastructure.Abstractions\Crest.Infrastructure.Abstractions.csproj" />
  </ItemGroup>

</Project>
