<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="$(PlatformSrcDir)OrchardCore\OrchardCore.Module.Targets\OrchardCore.Module.Targets.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore.Modules\OrchardCore.ContentFields\OrchardCore.ContentFields.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore\OrchardCore.ContentManagement\OrchardCore.ContentManagement.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore.Modules\OrchardCore.Contents\OrchardCore.Contents.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore\OrchardCore.Data\OrchardCore.Data.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore.Modules\OrchardCore.Flows\OrchardCore.Flows.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)OrchardCore\OrchardCore.Module.Targets\OrchardCore.Module.Targets.csproj" />
    <PackageReference Include="YesSql.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Domain/Crest.Parties.Domain.csproj" />
    <ProjectReference Include="../../Crest.Workflows/Domain/Crest.Workflows.Domain.csproj" />
    <ProjectReference Include="../../Crest.Workflows/engine/src/modules/Crest.Workflows.Core/Crest.Workflows.Core.csproj" />
    <ProjectReference Include="../../Crest.Workflows/engine/src/modules/Crest.Workflows.Engine/Crest.Workflows.Engine.csproj" />
    <ProjectReference Include="../../Crest.Server/Crest.csproj" />
    <ProjectReference Include="../../Crest.ContentPartLists/Crest.ContentPartLists.csproj" />
    <ProjectReference Include="../../Crest.Regions/Crest.Regions.csproj" />
  </ItemGroup>

  <Import Project="$(PlatformSrcDir)OrchardCore\OrchardCore.Module.Targets\OrchardCore.Module.Targets.targets" />
</Project>
