<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <!-- NuGet properties-->
    <Title>Crest Sms</Title>
    <Description>
      $(OCCMSDescription)

      The SMS module provides a way to send SMS messages.
    </Description>
    <PackageTags>$(PackageTags) PlatformCMS</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.DisplayManagement\Crest.DisplayManagement.csproj" />
    <ProjectReference Include="..\Crest.Module.Targets\Crest.Module.Targets.csproj" />
    <ProjectReference Include="..\Crest.Navigation.Core\Crest.Navigation.Core.csproj" />
    <ProjectReference Include="..\Crest.ResourceManagement\Crest.ResourceManagement.csproj" />
    <ProjectReference Include="..\Crest.Sms.Core\Crest.Sms.Core.csproj" />
    <ProjectReference Include="..\Crest.Workflows.Platform.Abstractions\Crest.Workflows.Platform.Abstractions.csproj" />
  </ItemGroup>
</Project>
