<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Crest.Notifications</RootNamespace>

    <!-- NuGet properties-->
    <Title>Crest Notifications Abstractions</Title>
    <Description>
      $(OCFrameworkDescription)

      Abstractions for Notifications.
    </Description>
    <PackageTags>$(PackageTags) PlatformFramework Abstractions</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Infrastructure.Abstractions\Crest.Infrastructure.Abstractions.csproj" />
  </ItemGroup>

</Project>
