<Project Sdk="Microsoft.NET.Sdk">


  <PropertyGroup>
    <RootNamespace>Crest.ResourceManagement</RootNamespace>
    <!-- NuGet properties-->
    <Title>Crest Roles Core</Title>
    <Description>$(OCFrameworkDescription)

    Core implementation for ResourceManagement module.</Description>
    <PackageTags>$(PackageTags) PlatformFramework</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Abstractions\Crest.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.ResourceManagement.Abstractions\Crest.ResourceManagement.Abstractions.csproj" />
  </ItemGroup>

</Project>
