<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- NuGet properties-->
    <Title>Crest</Title>
    <Description>$(OCFrameworkDescription)

    Implementation of Crest modular, multi-tenant ShellHost</Description>
    <PackageTags>$(PackageTags) PlatformFramework</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ncrontab" />
    <PackageReference Include="NodaTime" />
    <PackageReference Include="Fluid.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Abstractions\Crest.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Infrastructure.Abstractions\Crest.Infrastructure.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Localization.Abstractions\Crest.Localization.Abstractions.csproj" />
  </ItemGroup>

</Project>
