<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Crest.OpenApi</RootNamespace>
    <!-- NuGet properties-->
    <Title>Crest OpenApi Core</Title>
    <Description>
      $(OCFrameworkDescription)

      Core services for the OpenApi module.
    </Description>
    <PackageTags>$(PackageTags) PlatformFramework Api</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Infrastructure.Abstractions\Crest.Infrastructure.Abstractions.csproj" />
  </ItemGroup>

</Project>
