<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- NuGet properties-->
    <Title>Crest Queries Core</Title>
    <Description>$(OCCMSDescription)

    Core implementation for Queries.</Description>
    <PackageTags>$(PackageTags) PlatformCMS Queries</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Queries.Abstractions\Crest.Queries.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YesSql.Core" />
  </ItemGroup>

</Project>
