<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <!-- NuGet properties-->
    <Title>Crest Settings</Title>
    <Description>$(OCCMSDescription)

    The settings module creates site settings.</Description>
    <PackageTags>$(PackageTags) PlatformCMS</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Admin.Abstractions\Crest.Admin.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Data.Abstractions\Crest.Data.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Deployment.Abstractions\Crest.Deployment.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.DisplayManagement\Crest.DisplayManagement.csproj" />
    <ProjectReference Include="..\Crest.Module.Targets\Crest.Module.Targets.csproj" />
    <ProjectReference Include="..\Crest.Navigation\Crest.Navigation.csproj" />
    <ProjectReference Include="..\Crest.Liquid.Abstractions\Crest.Liquid.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Recipes.Abstractions\Crest.Recipes.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Roles\Crest.Roles.csproj" />
    <ProjectReference Include="..\Crest.Setup.Abstractions\Crest.Setup.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Abstractions\Crest.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Settings.Abstractions\Crest.Settings.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Access.Abstractions\Crest.Access.Abstractions.csproj" />
  </ItemGroup>

</Project>
