<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.ContentFields" />
    <PackageReference Include="OrchardCore.ContentManagement" />
    <PackageReference Include="OrchardCore.Contents" />
    <PackageReference Include="OrchardCore.Data" />
    <PackageReference Include="OrchardCore.Infrastructure.Abstractions" />
    <PackageReference Include="OrchardCore.Module.Targets" />
    <PackageReference Include="OrchardCore.Roles.Core" />
    <PackageReference Include="OrchardCore.Users" />
    <PackageReference Include="OrchardCore.Users.Core" />
    <PackageReference Include="YesSql.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Domain/Crest.Members.Domain.csproj" />
    <ProjectReference Include="../../Crest.Parties/Server/Crest.Parties.csproj" />
    <ProjectReference Include="../../OrchardCore.Crest.Server/OrchardCore.Crest.csproj" />
    <ProjectReference Include="../../Crest.ContentPartLists/Crest.ContentPartLists.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Crest.Members.Tests" />
  </ItemGroup>
</Project>
