<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(PlatformSrcDir)Crest.Module.Targets\Crest.Module.Targets.props" />

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
        <IsPackable>true</IsPackable>
        <PackageId>Crest.Workflows.UI</PackageId>
        <PackageTags>Crest;Crest;Workflows;UI</PackageTags>
        <Description>Provides UI-related workflow activities for Crest. Includes activities for displaying notifications and interacting with the user interface.</Description>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations"/>
        <ProjectReference Include="$(PlatformSrcDir)Crest.DisplayManagement\Crest.DisplayManagement.csproj" />
        <ProjectReference Include="$(PlatformSrcDir)Crest.Module.Targets\Crest.Module.Targets.csproj" />
    </ItemGroup>

    <ItemGroup Label="Crest.Workflows">
        <PackageReference Include="Crest.Workflows.Engine"/>
    </ItemGroup>
</Project>
