<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\src\Crest.Build\Crest.Commons.props" />
  <Import Project="..\..\..\src\Crest.Module.Targets\Crest.Module.Targets.props" />

  <PropertyGroup>
    <TargetFrameworks>$(CommonTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Crest.Module.Targets\Crest.Module.Targets.csproj" />
  </ItemGroup>

  <Import Project="..\..\..\src\Crest.Module.Targets\Crest.Module.Targets.targets" />
  <Import Project="..\..\..\src\Crest.Build\Crest.Commons.targets" />

</Project>
