<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Crest.Admin</RootNamespace>

    <!-- NuGet properties-->
    <Title>Crest Admin Abstractions</Title>
    <Description>$(OCCMSDescription)

    Abstractions of Crest Admin Module.</Description>
    <PackageTags>$(PackageTags) PlatformCMS Abstractions</PackageTags>

  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Abstractions\Crest.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Infrastructure.Abstractions\Crest.Infrastructure.Abstractions.csproj" />
  </ItemGroup>

</Project>
