<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>Crest Flows Core</Title>
    <Description>
      $(OCCMSDescription)

      Core project for the Flows module.
    </Description>
    <PackageTags>$(PackageTags) PlatformCMS</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.ContentManagement.Abstractions\Crest.ContentManagement.Abstractions.csproj" />
  </ItemGroup>

</Project>
