<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
     <!-- NuGet properties-->
    <Title>Crest GraphQL Apis</Title>
    <Description>$(OCFrameworkDescription)

    Provies apis using the GraphQL Specification.</Description>
    <PackageTags>$(PackageTags) PlatformFramework</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GraphQL" />
    <PackageReference Include="GraphQL.DataLoader" />
    <PackageReference Include="GraphQL.MicrosoftDI" />
    <PackageReference Include="GraphQL.SystemTextJson" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YesSql.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Admin.Abstractions\Crest.Admin.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Apis.GraphQL.Abstractions\Crest.Apis.GraphQL.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.DisplayManagement\Crest.DisplayManagement.csproj" />
    <ProjectReference Include="..\Crest.Module.Targets\Crest.Module.Targets.csproj" />
    <ProjectReference Include="..\Crest.Navigation\Crest.Navigation.csproj" />
    <ProjectReference Include="..\Crest.ResourceManagement\Crest.ResourceManagement.csproj" />
  </ItemGroup>

</Project>
