<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="$(PlatformSrcDir)Crest.Module.Targets\Crest.Module.Targets.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(PlatformSrcDir)Crest.ContentFields\Crest.ContentFields.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)Crest.ContentManagement\Crest.ContentManagement.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)Crest.Contents\Crest.Contents.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)Crest.Data\Crest.Data.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)Crest.Infrastructure.Abstractions\Crest.Infrastructure.Abstractions.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)Crest.Module.Targets\Crest.Module.Targets.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)Crest.Roles.Core\Crest.Roles.Core.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)Crest.Users\Crest.Users.csproj" />
    <ProjectReference Include="$(PlatformSrcDir)Crest.Users.Core\Crest.Users.Core.csproj" />
    <PackageReference Include="YesSql.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Domain/Crest.Members.Domain.csproj" />
    <ProjectReference Include="../../Crest.Parties/Server/Crest.Parties.csproj" />
    <ProjectReference Include="../../Crest.Server/Crest.Server.csproj" />
    <ProjectReference Include="../../Crest.ContentPartLists/Crest.ContentPartLists.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Crest.Members.Tests" />
  </ItemGroup>
</Project>
