<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Crest.Lucene</RootNamespace>
    <!-- NuGet properties-->
    <Title>Crest Lucene Abstractions</Title>
    <Description>$(OCCMSDescription)

    Abstractions for the Lucene module.</Description>
    <PackageTags>$(PackageTags) PlatformCMS Abstractions</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lucene.Net" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Indexing.Abstractions\Crest.Indexing.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Infrastructure.Abstractions\Crest.Infrastructure.Abstractions.csproj" />
  </ItemGroup>

</Project>
