<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Description>
			Provides scheduling activities such as Timer, Delay and StartAt.
		</Description>
		<PackageTags>crestWorkflows extension module scheduling</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Cronos" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Crest.Workflows.Runtime\Crest.Workflows.Runtime.csproj" />
	</ItemGroup>

</Project>
