<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <RootNamespace>Crest.Notifications</RootNamespace>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>

    <!-- NuGet properties-->
    <Title>Crest Notifications</Title>
    <Description>
      $(OCFrameworkDescription)

      Notifications module provides a way to send notifications to a user.
    </Description>
    <PackageTags>$(PackageTags) PlatformFramework</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Admin.Abstractions\Crest.Admin.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.ContentManagement.Display\Crest.ContentManagement.Display.csproj" />
    <ProjectReference Include="..\Crest.Contents.Abstractions\Crest.Contents.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.ContentManagement\Crest.ContentManagement.csproj" />
    <ProjectReference Include="..\Crest.Module.Targets\Crest.Module.Targets.csproj" />
    <ProjectReference Include="..\Crest.Navigation\Crest.Navigation.csproj" />
    <ProjectReference Include="..\Crest.ResourceManagement\Crest.ResourceManagement.csproj" />
    <ProjectReference Include="..\Crest.Users\Crest.Users.csproj" />
    <ProjectReference Include="..\Crest.Workflows\Abstractions\Crest.Workflows.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Workflows\engine\src\modules\Crest.Workflows.Core\Crest.Workflows.Core.csproj" />
    <ProjectReference Include="..\Crest.Workflows\engine\src\modules\Crest.Workflows.Engine\Crest.Workflows.Engine.csproj" />
    <ProjectReference Include="..\Crest.ContentManagement.Abstractions\Crest.ContentManagement.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Email.Abstractions\Crest.Email.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Infrastructure\Crest.Infrastructure.csproj" />
    <ProjectReference Include="..\Crest.Notifications.Abstractions\Crest.Notifications.Abstractions.csproj" />
  </ItemGroup>

</Project>
