<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <!-- NuGet properties-->
    <Title>Crest Media ImageSharp</Title>
    <Description>$(OCCMSDescription)

    Provides an ImageSharp (v3) based implementation of the media image processing engine.</Description>
    <PackageTags>$(PackageTags) PlatformCMS ContentManagement</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Crest.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Module.Targets\Crest.Module.Targets.csproj" />
    <ProjectReference Include="..\Crest.Media\Crest.Media.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>

</Project>
