<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(PlatformSrcDir)Crest.Module.Targets\Crest.Module.Targets.props" />

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <IsPackable>true</IsPackable>
        <PackageId>Crest.Workflows.Timers</PackageId>
        <PackageTags>Crest;Crest;Workflows;Timers</PackageTags>
        <Description>Provides timer services and scheduling activities for Crest.Workflows workflows in Crest. Includes Quartz.NET-based scheduling for clustered deployments.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations"/>
        <PackageReference Include="ncrontab"/>
        <ProjectReference Include="$(PlatformSrcDir)Crest.Module.Targets\Crest.Module.Targets.csproj" />
        <PackageReference Include="Quartz"/>
    </ItemGroup>

    <ItemGroup Label="Crest.Workflows">
        <PackageReference Include="Crest.Workflows.Scheduling"/>
        <PackageReference Include="Crest.Workflows.Scheduling.Quartz"/>
        <PackageReference Include="Crest.Workflows.Engine"/>
    </ItemGroup>
</Project>
