<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Crest.HealthChecks</RootNamespace>
    <!-- NuGet properties-->
    <Title>Crest Health Chekcs Abstractions</Title>
    <Description>
      $(OCCMSDescription)

      Abstractions for health checks
    </Description>
    <PackageTags>$(PackageTags) Crest Framework Health Checks Abstractions</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
