<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>
            Provides HTTP activities to listen for and send out HTTP requests.
        </Description>
        <PackageTags>crestWorkflows module http activities</PackageTags>
    </PropertyGroup>

    <ItemGroup>
		<PackageReference Include="FluentStorage" />
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
        <PackageReference Include="Microsoft.Extensions.Resilience" />
        <PackageReference Include="Polly" />
		
		<!-- Used to resolve the FluentStoage package warning. -->
    </ItemGroup>

    <ItemGroup>
		<ProjectReference Include="..\Crest.Workflows.Expressions.JavaScript\Crest.Workflows.Expressions.JavaScript.csproj" />
		<ProjectReference Include="..\Crest.Workflows.Expressions.Liquid\Crest.Workflows.Expressions.Liquid.csproj" />
		<ProjectReference Include="..\Crest.Workflows.Resilience\Crest.Workflows.Resilience.csproj" />
		<ProjectReference Include="..\Crest.Workflows.SasTokens\Crest.Workflows.SasTokens.csproj" />
		<ProjectReference Include="..\Crest.Workflows.Api\Crest.Workflows.Api.csproj" />
		<ProjectReference Include="..\Crest.Workflows.Runtime\Crest.Workflows.Runtime.csproj" />
    </ItemGroup>

</Project>
