<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Crest.AzureAI</RootNamespace>
    <!-- NuGet properties-->
    <Title>Crest Azure AI Search Core</Title>
    <Description>$(OCCMSDescription)

    Core Implementation for Azure AI Search module.</Description>
    <PackageTags>$(PackageTags) PlatformCMS</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Search.Documents" />
    <PackageReference Include="Microsoft.Extensions.Azure" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Indexing\Crest.Indexing.csproj" />
    <ProjectReference Include="..\Crest.Abstractions\Crest.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.ContentLocalization.Abstractions\Crest.ContentLocalization.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.ContentManagement.Abstractions\Crest.ContentManagement.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.ContentPreview.Abstractions\Crest.ContentPreview.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Contents.Core\Crest.Contents.Core.csproj" />
    <ProjectReference Include="..\Crest.Deployment.Abstractions\Crest.Deployment.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Indexing.Core\Crest.Indexing.Core.csproj" />
    <ProjectReference Include="..\Crest.Infrastructure.Abstractions\Crest.Infrastructure.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Search.Abstractions\Crest.Search.Abstractions.csproj" />
  </ItemGroup>

</Project>
