<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="OrchardCore.Contents" />
    <PackageReference Include="OrchardCore.Module.Targets" />
    <PackageReference Include="OrchardCore.ContentManagement" />
    <PackageReference Include="OrchardCore.Title" />
  </ItemGroup>

  <ItemGroup Label="Elsa">
    <PackageReference Include="Elsa.Expressions.JavaScript" />
    <PackageReference Include="Elsa.Workflows.Core" />
    <PackageReference Include="Elsa.Workflows.Management" />
    <PackageReference Include="Elsa.Workflows.Runtime" />
    <PackageReference Include="Elsa" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrchardCore.Crest.Workflows\OrchardCore.Crest.Workflows.csproj" />
  </ItemGroup>

</Project>
