<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <!-- NuGet properties-->
    <Title>Crest OpenId</Title>
    <Description>$(OCCMSDescription)

    Provides OpenId Connect client, server and management features.</Description>
    <PackageTags>$(PackageTags) PlatformCMS OpenId</PackageTags>
    
    <!-- Required to build on net10.0 with validation interceptors until it's part of the SDK -->
    <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.Http.Validation.Generated</InterceptorsNamespaces>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.Admin.Abstractions\Crest.Admin.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.ContentManagement.Abstractions\Crest.ContentManagement.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Data.Abstractions\Crest.Data.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.Deployment.Abstractions\Crest.Deployment.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.DisplayManagement\Crest.DisplayManagement.csproj" />
    <ProjectReference Include="..\Crest.Module.Targets\Crest.Module.Targets.csproj" />
    <ProjectReference Include="..\Crest.Navigation.Core\Crest.Navigation.Core.csproj" />
    <ProjectReference Include="..\Crest.OpenId.Core\Crest.OpenId.Core.csproj" />
    <ProjectReference Include="..\Crest.RateLimits.Core\Crest.RateLimits.Core.csproj" />
    <ProjectReference Include="..\Crest.Recipes.Abstractions\Crest.Recipes.Abstractions.csproj" />
    <ProjectReference Include="..\Crest.ResourceManagement\Crest.ResourceManagement.csproj" />
    <ProjectReference Include="..\Crest.Roles.Core\Crest.Roles.Core.csproj" />
    <ProjectReference Include="..\Crest.Users.Abstractions\Crest.Users.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" />
    <PackageReference Include="OpenIddict.Server.AspNetCore" />
    <PackageReference Include="OpenIddict.Server.DataProtection" />
    <PackageReference Include="OpenIddict.Validation.AspNetCore" />
    <PackageReference Include="OpenIddict.Validation.DataProtection" />
    <PackageReference Include="OpenIddict.Validation.SystemNetHttp" />
  </ItemGroup>

</Project>
