<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Crest.Html</RootNamespace>
    <!-- NuGet properties-->
    <Title>Crest Html Abstractions</Title>
    <Description>$(OCCMSDescription)

    Abstractions for the Html module.</Description>
    <PackageTags>$(PackageTags) PlatformCMS Abstractions</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Shortcodes" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crest.ContentManagement.Abstractions\Crest.ContentManagement.Abstractions.csproj" />
  </ItemGroup>

</Project>
